### ISSUE TITLE
Suggestion: Reincorporate 'Find Cheats' option

### ISSUE THREAD

**Issue by 8uuu** [Marat-Tanalin/bsnes-mt#27]
Regards mt. The original bsnes has the option to add already preset cheats in some games. 

![Desktop 5-01-2023 11-55-38-800](https://user-images.githubusercontent.com/93301921/210849231-4c4d714b-9ded-48f6-ba98-19b3dd09cf62.png)

However in this version this feature seems to be missing, so I think it would be a good idea to add it in the future.
![Desktop 5-01-2023 13-00-28-402](https://user-images.githubusercontent.com/93301921/210850158-8b4cb139-90bc-43f7-b011-3c11a6536f1f.png)

**Comment by Marat-Tanalin** [comment]
Try just to extract/move bsnes-mt executable into bsnes folder so that the cheat database (apparently `Database\Cheat Codes.bml` file not bundled with bsnes-mt) is available to bsnes-mt too.

**Comment by 8uuu** [comment]
It worked perfectly, thanks. But just out of curiosity, why didn't you include the database folder in the releases? Is it forbidden or something like that?

**Comment by Marat-Tanalin** [comment]
There are multiple reasons. If bundle databases, why not bundle shaders? Bundling shaders would make the distro much larger, the databases and shaders would need to be updated/synchronized with bsnes on a regular basis, the repo would have to contain them, etc.

I prefer just to provide improved/extra features without needlessly spending time on anything out of my main focus in this project.
