### ISSUE TITLE
(Auto) region select not work in native open file dialog

### ISSUE THREAD

**Issue by Max833** [Marat-Tanalin/bsnes-mt#3]
https://github.com/bsnes-emu/bsnes/issues/44

Do you think you can fix this? Maybe it is a good idea to implement the region select like in Mesen-S?

![3!](https://user-images.githubusercontent.com/53529402/88483195-957f8e80-cf66-11ea-87f6-c38ca09c0663.jpg)

**Comment by Marat-Tanalin** [comment]
Everything is possible. Please provide a self-contained specific-enough description not relying on external sources.

**Comment by Max833** [comment]
Exactly, yes. It always chooses NTSC. Sorry, I should have write about this instead of just link to the issue.

**Comment by Marat-Tanalin** [comment]
Fixed by 487a849. No user interface for choosing a specific region; just autodetection when neither NTSC nor PAL are specified — as in case of using native file dialog.
