### ISSUE TITLE
Suggestion: Update Drivers

### ISSUE THREAD

**Issue by IPeluchito** [Marat-Tanalin/bsnes-mt#4]
Is it possible that drivers could be updated to **DirectX 11 / Vulkan**, update **XAudio** and full **Xinput** support? This in order to improve performance and compatibility with modern platforms, hopefully it could be possible ...

**Comment by Marat-Tanalin** [comment]
Technically possible, though unlikely to happen. Aside from that I’m not experienced enough in&nbsp;graphics and audio programming, it’s not quite clear what benefits this would bring.

Could you provide specific cases (except for shaders’ post-processing) where GPU (graphics card), not&nbsp;CPU (central processor), is a&nbsp;bottleneck in&nbsp;terms of&nbsp;performance?

What would be exact advantages of&nbsp;updating XAudio?

How exactly non-full is the&nbsp;XInput support in&nbsp;its current state?

**Comment by IPeluchito** [comment]
A new generation of emulators is emerging that not only emulates real hardware but also improves it with modern and advanced techniques, it is not surprising that in a short time we will see emulators with **AI scaling**, **HDR**, **Raytracing**, **AI sound**, etc. that is why that it is necessary to update libraries like **Vulkan**, which opens up many more possibilities in that sense, in addition to improving performance since it works at a low level, it is multi-core and it is multiplatform ...

**Xaudio** has better sound quality and effects than the other drivers integrated in **Bsnes** but it is outdated (**2.1**) ... **DIRECTX 9 JUN 2010** includes version **2.7** **!!!**

**Xinput** automatically recognizes all the controls and configures the buttons automatically, there is no need to do anything else ...

Well that's my opinion, thanks for your time and effort ...

**Comment by Marat-Tanalin** [comment]
Thanks. Sounds somewhat theoretical. ;-) HDR, Ray Tracing and probably AI scaling are unlikely applicable to SNES games. Not sure what AI sound is supposed to mean.

Newer version of XAudio does not necessarily mean it has improvements in sound quality in the way it’s used in this emulator.

Automatic controller configuration sounds rather interesting, though not something I would be willing to spend time on.

For now I’m not interested in any of these, but keeping this proposal open as a potential way for further improvements.
