### ISSUE TITLE
This is the best emulator for SNES I have ever seen.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Marat-Tanalin/bsnes-mt#9]
I could not believe when I could play LAGLESS super r type. All I had to do was clock the console by 400 percent and the game runs skipless! Kudos to the dev seriously :D

**Comment by P3rf3ctXZer0** [comment]
https://i.imgur.com/hOmCOVH.png

**Comment by Marat-Tanalin** [comment]
Well, nice, but:

* if this is just about the overclocking feature, the same feature was in the original bsnes, and it’s untouched in bsnes-mt;
* this is certainly not an issue, so I’m closing it.

Feel free to add another comment if the result you described is specific to bsnes-**mt** and not to original bsnes — that would be interesting. :-)

Good luck.
